# Generated by Django 5.1.1 on 2024-09-23 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=255, unique=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Users')])),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id_penulis', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/images/penulis/')),
                ('nama_penulis', models.CharField(max_length=255)),
                ('biodata', models.TextField()),
                ('tanggal_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('alamat', models.CharField(blank=True, max_length=255)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/images/profil/')),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id_buku', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255, unique=True)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('tahun_terbit', models.IntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='static/images/cover/')),
                ('kategori', models.ManyToManyField(related_name='buku', to='xue.kategori')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xue.penulis')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_keranjang', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xue.buku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xue.users')),
            ],
        ),
    ]
